stages:
  - lint
  - test
  - build

lint-test-job:
  stage: lint
  script:
    - echo "Checking code for any mistakes..."
    - yarn prettier-diff
    - yarn type-check


unit-test-job:
  stage: test
  script:
    - echo "Testing Code ..."
    - yarn test

build-job:
  stage: build
  script:
    - echo "Building the code..."
    - yarn build



