#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn prettier-diff && yarn build

if [[ $(git ls-files -m) ]]; then
  echo "files modified unexpectedly, did you forget to run yarn prettier-format or yarn build?"
  exit 1
fi
